FROM       centos:6
MAINTAINER Jason Swank <docker@scalene.net>

RUN yum -y groupinstall "Development Tools" \
  && yum clean all

RUN yum install -y \
  epel-release rpmdevtools curl tar createrepo \
  && yum clean all
